#!/bin/bash

if [[ -z $1 && $1 != "CNCLD" ]]; then
  echo "Usage: omarchy-theme-set <theme-name>"
  exit 1
fi

THEMES_DIR="$HOME/.config/omarchy/themes/"
CURRENT_THEME_DIR="$HOME/.config/omarchy/current/theme"

THEME_NAME=$(echo "$1" | sed -E 's/<[^>]+>//g' | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
THEME_PATH="$THEMES_DIR/$THEME_NAME"

# Check if the theme entered exists
if [[ ! -d "$THEME_PATH" ]]; then
  echo "Theme '$THEME_NAME' does not exist in $THEMES_DIR"
  exit 1
fi

# Update theme symlinks
ln -nsf "$THEME_PATH" "$CURRENT_THEME_DIR"

# Change background with theme
omarchy-theme-bg-next

# Update zellij theme
if [[ -d "$HOME/.config/zellij" ]]; then
  sed -i "s/^theme \".*\"/theme \"$THEME_NAME\"/" "$HOME/.config/zellij/config.kdl"
fi

# Update aerc theme
omarchy-update-aerc

# Restart components to apply new theme
omarchy-restart-waybar
omarchy-restart-swayosd
hyprctl reload
pkill -SIGUSR2 btop
makoctl reload

# Change gnome, browser, vscode themes
omarchy-theme-set-terminal
omarchy-theme-set-gnome
omarchy-theme-set-eza
omarchy-theme-set-browser
omarchy-theme-set-vscode
